# Extra pages: simulator, contracts, actions. Called from build.py with the shared context.
import json
def build_extra(page, CH, runway):
    TYPES=[{"t":"A / E","n":58,"m":7432,"c2":32357},{"t":"A1 / E1","n":16,"m":7499,"c2":32649},{"t":"B / F","n":58,"m":6921,"c2":30133},{"t":"B1 / F1","n":16,"m":6988,"c2":30424},{"t":"C","n":72,"m":6058,"c2":26375},{"t":"D1","n":66,"m":5723,"c2":24917},{"t":"D","n":8,"m":5381,"c2":23428}]
    sim = """<section><div class="eyebrow">Five options, one model</div><h1>Try the options</h1>
<p class="lead">Each option is run through the same cash model. Change the assumptions and see what happens to the gap, to the reserves, and to your bill.</p>
<div class="tiles" id="gapTiles"></div></section>
<section><h2>Does it close the gap?</h2><div class="opts" id="optCards"></div>
<p class="small">"This year" is August 2026 to March 2027. "Next year" is April 2027 to March 2028, with all interest counted and tax provided. Click a card to select it.</p></section>
<section><h2>Assumptions</h2>
<div class="cards" style="grid-template-columns:repeat(auto-fit,minmax(240px,1fr))">
<div class="card"><h3>Committee option</h3><p class="small">Base increase: <strong><span id="pctLabel">20</span>%</strong></p><input type="range" id="pct" min="0" max="45" step="1" value="20" style="width:100%"><p class="small" style="margin-top:6px">The other options are fixed: Sub-Committee +10.1% with GST inside the bill; Option 1 +39.4%; Option 2 an annual contribution.</p><input type="hidden" id="preset" value="mc"></div>
<div class="card"><h3>GST above ₹7,500</h3>
<label><input type="radio" name="gst" value="whole" checked> On the whole amount</label>
<label><input type="radio" name="gst" value="excess"> Only on the part above ₹7,500</label>
<label style="margin-top:6px"><input type="checkbox" id="itc" checked> Association reclaims GST on its own bills</label></div>
<div class="card"><h3>Timing</h3>
<label><input type="radio" name="eff" value="oct" checked> New rate from 1 Oct, difference billed in Nov</label>
<label><input type="radio" name="eff" value="jan"> New rate from 1 Jan</label>
<label class="small" style="margin-top:6px"><input type="checkbox" id="rep2" checked> Option 2 repeated next year</label></div>
<div class="card"><h3>Costs</h3>
<p class="small">Savings from tenders, from Jan 2027<br><select id="sav"><option value="0">None</option><option value="15">₹15 L a year</option><option value="25" selected>₹25 L a year</option><option value="30">₹30 L a year</option></select></p>
<p class="small">Spending base<br><select id="base"><option value="mc" selected>₹26 L a month plus lift contract and tax</option><option value="tr">₹33 L a month flat (Treasurer)</option></select></p>
<p class="small">Tax on interest<br><select id="tax"><option value="2.5">₹2.5 L a quarter (current)</option><option value="5.25" selected>₹5.25 L a quarter (correct provision)</option></select></p></div>
</div></section>
<section><h2>Your bill under the selected option</h2><div class="tablewrap"><table><thead><tr><th>Flat type</th><th class="num">Flats</th><th class="num">Today / month</th><th class="num">New base</th><th class="num">GST</th><th class="num">Total / month</th><th class="num">Extra per year</th></tr></thead><tbody id="flatRows"></tbody></table></div><p class="small" id="flatNote"></p></section>
<section><h2>Cash in the account</h2><div class="chartbox"><canvas id="cSim" height="110"></canvas></div><p class="small">Starts from ₹34.8 L on 31 July 2026. Below zero, the reserves are used.</p></section>
<section><h2>Side by side</h2><div class="tablewrap"><table><thead><tr><th>Option</th><th class="num">A-type flat / month</th><th class="num">Extra per year</th><th class="num">Raised this year</th><th class="num">From reserves this year</th><th class="num">Next year</th><th>Verdict</th></tr></thead><tbody id="cmpRows"></tbody></table></div></section>
<section><h2>How the model works</h2><ol class="steps"><li>Spending: ₹26 L a month, plus ₹8 L for the lift contract in June and December, plus tax each quarter. Or ₹33 L flat, the Treasurer's figure. Savings reduce it from January 2027.</li><li>Income in a quiet month: ₹1.8 L late maintenance, ₹0.8 L rentals and fees, ₹1.9 L HDFC interest, ₹0.5 L Sobha interest. In a billing month: 92% of the quarter's bills.</li><li>GST collected goes to the government. If input credit is on, the association keeps its own vendor GST in proportion to taxable billing.</li><li>Option 2 nets ₹69.5 L after GST, collected in November. The Sub-Committee's 10.1% is applied to the bill with GST inside it, as in their report.</li><li>Next year adds ICICI interest (₹38 L) and deducts tax on all interest.</li></ol></section>"""
    simjs = CH + "const TYPES=" + json.dumps(TYPES) + ";" + r"""
const START=34.8, MONTHS=[];(()=>{let y=2026,m=8;for(let i=0;i<20;i++){MONTHS.push({y,m,label:new Date(y,m-1,1).toLocaleString("en-IN",{month:"short"})+" "+String(y).slice(2)});m++;if(m>12){m=1;y++;}}})();
const P={asis:{pct:0,inside:false,contrib:false},sc:{pct:10.1,inside:true,contrib:false},mc:{pct:null,inside:false,contrib:false},opt1:{pct:39.37,inside:false,contrib:false},opt2:{pct:0,inside:false,contrib:true}};
function flatCalc(t,pct,inside,gst){ let base,total;
  if(inside){ total=t.m*(1+pct/100); base= total>7500 ? (gst==="whole"? total/1.18 : total-((total-7500)*0.18/1.18)) : total; }
  else { base=t.m*(1+pct/100); const g= base>7500 ? (gst==="whole"? base*0.18 : (base-7500)*0.18) : 0; total=base+g; }
  return {base,gstAmt:total-base,total}; }
function run(o){
  const rows=TYPES.map(t=>({t,...flatCalc(t,o.pct,o.inside,o.gst)}));
  const monthlyBaseNew=rows.reduce((a,r)=>a+r.base*r.t.n,0), monthlyBaseOld=TYPES.reduce((a,t)=>a+t.m*t.n,0);
  const taxableShare=rows.reduce((a,r)=>a+(r.gstAmt>0?(o.gst==="whole"?r.base:Math.max(0,r.base-7500))*r.t.n:0),0)/monthlyBaseNew;
  const itcYear=(o.itc && rows.some(r=>r.gstAmt>0)) ? 35*taxableShare : 0;
  const contribNet=o.contrib? TYPES.reduce((a,t)=>a+t.c2/1.18*t.n,0)/1e5 : 0;
  let bal=START, series=[], minB=1e9, minM="", b27=0,b28=0;
  MONTHS.forEach((mo)=>{
    const newRateOn = o.eff==="oct" ? (mo.y>2026 || mo.m>=10) : (mo.y>=2027);
    let inn=1.8+0.8+1.91+0.5;
    if([10,1,4,7].includes(mo.m)){ const q=(newRateOn?monthlyBaseNew:monthlyBaseOld)*3/1e5; inn+=0.92*q; if(newRateOn) inn+=itcYear/4; }
    if(o.eff==="oct" && mo.y===2026 && mo.m===11) inn+=0.92*(monthlyBaseNew-monthlyBaseOld)*3/1e5;
    if(o.contrib && mo.m===11 && (mo.y===2026 || (mo.y===2027 && o.rep2))) inn+=0.92*contribNet;
    let out= o.base==="tr" ? 33 : 26;
    if(o.base==="mc"){ if([9,12,3,6].includes(mo.m)) out+=o.taxQ; if([12,6].includes(mo.m)) out+=8; }
    if(mo.y>=2027) out-=o.sav/12;
    bal=bal+inn-out; series.push(bal); if(bal<minB){minB=bal;minM=mo.label;}
    if(mo.y===2027&&mo.m===3) b27=bal; if(mo.y===2028&&mo.m===3) b28=bal; });
  const collections=monthlyBaseNew*12*0.98/1e5 + (o.contrib&&o.rep2?contribNet:0);
  const income=collections+22.9+38+6+9.6+itcYear-(o.taxQ*4);
  const spend=(o.base==="tr"?33*12:26*12+16)-o.sav;
  return {rows,monthlyBaseNew,itcYear,contribNet,series,minB,minM,b27,b28,surplus:income-spend,taxableShare}; }
function read(){ const preset=document.getElementById("preset").value; const p=P[preset]; const pct=p.pct==null?+document.getElementById("pct").value:p.pct;
  return {preset,pct,inside:p.inside,contrib:p.contrib,gst:document.querySelector('input[name=gst]:checked').value,itc:document.getElementById("itc").checked,eff:document.querySelector('input[name=eff]:checked').value,sav:+document.getElementById("sav").value,base:document.getElementById("base").value,taxQ:+document.getElementById("tax").value,rep2:document.getElementById("rep2").checked}; }
const inr=n=>"₹"+Math.round(n).toLocaleString("en-IN"); const L=n=>(n<0?"−":"")+"₹"+Math.abs(n).toFixed(1)+" L";
let chart;
const NM={asis:"Carry on as we are",sc:"Sub-Committee: +10.1%",mc:"Committee option",opt1:"GBM Option 1: +39.4%",opt2:"GBM Option 2: annual contribution"};
function optOf(o,k){ const p=P[k]; return {...o,preset:k,pct:p.pct==null?+document.getElementById("pct").value:p.pct,inside:p.inside,contrib:p.contrib}; }
function verdict(rr){ if(rr.surplus<0) return {c:"no",t:"Not enough. Still short next year."}; if(rr.surplus<15) return {c:"mid",t:"Just balances next year. No buffer."}; return {c:"ok",t:"Balances next year, with a buffer."}; }
function render(){ const o=read(); const r=run(o); const asis=run(optOf(o,"asis"));
  document.getElementById("pctLabel").textContent=document.getElementById("pct").value;
  const tile=(c,k,v,d)=>'<div class="tile '+c+'"><div class="k">'+k+'</div><div class="v">'+v+'</div><div class="d">'+d+'</div></div>';
  const gapNow=Math.max(0,-asis.b27);
  document.getElementById("gapTiles").innerHTML=tile("crit","If nothing changes: from reserves this year",L(gapNow),"August 2026 to March 2027")+tile("crit","If nothing changes: next year",L(asis.surplus),"full year, interest counted, tax provided")+tile("","Maintenance today","₹"+(TYPES.reduce((a,t)=>a+t.m*t.n,0)*12/1e5).toFixed(0)+" L/yr","294 flats")+tile("","Spending next year","₹"+((o.base==="tr"?33*12:26*12+16)-o.sav)+" L/yr","after savings");
  const keys=["asis","sc","mc","opt1","opt2"];
  document.getElementById("optCards").innerHTML=keys.map(k=>{ const oo=optOf(o,k); const rr=run(oo); const a=rr.rows[0]; const raised=Math.max(0,rr.b27-asis.b27); const fromRes=Math.max(0,-rr.b27); const cov=gapNow?Math.min(1,raised/gapNow):0; const v=verdict(rr); const extra=(a.total-a.t.m)*12+(oo.contrib?a.t.c2:0); const nm=k==="mc"?NM[k]+" +"+oo.pct+"%":NM[k];
    return '<div class="opt'+(k===o.preset?' sel':'')+'" data-k="'+k+'" role="button" tabindex="0"><h3>'+nm+'</h3><div class="bill">'+inr(a.total)+'<span class="small"> /month, A-type</span></div><div class="sub">'+(extra>0?inr(extra)+" more per year":"no change")+(oo.contrib?" (annual contribution)":"")+'</div><div class="row"><span>Raises this year</span><b>'+L(raised)+'</b></div><div class="gapbar"><span style="width:'+(cov*100)+'%"></span></div><div class="row" style="border:0;padding-top:0"><span>Still from reserves this year</span><b class="'+(fromRes>0?"neg":"pos")+'">'+L(fromRes)+'</b></div><div class="row"><span>Next year</span><b class="'+(rr.surplus<0?"neg":"pos")+'">'+L(rr.surplus)+'</b></div><div class="verdict '+v.c+'">'+v.t+'</div></div>'; }).join("");
  document.querySelectorAll(".opt").forEach(el=>{ const f=()=>{document.getElementById("preset").value=el.dataset.k; render();}; el.onclick=f; el.onkeydown=e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();f();}}; });
  document.getElementById("flatRows").innerHTML=r.rows.map(x=>'<tr><td>'+x.t.t+'</td><td class="num">'+x.t.n+'</td><td class="num">'+inr(x.t.m)+'</td><td class="num">'+inr(x.base)+'</td><td class="num">'+(x.gstAmt?inr(x.gstAmt):"—")+'</td><td class="num"><strong>'+inr(x.total)+'</strong></td><td class="num">'+inr((x.total-x.t.m)*12+(o.contrib?x.t.c2:0))+'</td></tr>').join("");
  document.getElementById("flatNote").textContent=o.contrib?"Option 2: the monthly bill does not change. The extra per year is the annual contribution, including 18% GST.":(o.inside?"Sub-Committee method: the increase is on the whole bill and GST is taken out of it, so the association nets less than the bill.":"GST applies once the base crosses ₹7,500 a month.");
  const labels=MONTHS.map(m=>m.label); if(chart) chart.destroy();
  chart=new Chart(document.getElementById("cSim"),{type:"line",data:{labels,datasets:[{label:NM[o.preset]+(o.preset==="mc"?" +"+o.pct+"%":""),data:r.series.map(v=>+v.toFixed(1)),borderColor:css("--accent"),backgroundColor:css("--accent")+"1f",fill:true,tension:.3,pointRadius:3,pointBackgroundColor:r.series.map(v=>v<0?css("--crit"):css("--accent"))},{label:"Carry on as we are",data:asis.series.map(v=>+v.toFixed(1)),borderColor:css("--c7"),borderDash:[4,4],borderWidth:1.5,pointRadius:0,tension:.3}]},options:{scales:{y:{ticks:{callback:v=>v+" L"},grid:{color:css("--line-soft")}},x:{grid:{display:false}}},plugins:{legend:{position:"bottom",labels:{boxWidth:10,font:{size:12}}}}}});
  document.getElementById("cmpRows").innerHTML=keys.map(k=>{const oo=optOf(o,k); const rr=run(oo); const a=rr.rows[0]; const raised=Math.max(0,rr.b27-asis.b27); const fromRes=Math.max(0,-rr.b27); const v=verdict(rr); const nm=k==="mc"?NM[k]+" +"+oo.pct+"%":NM[k];
    return '<tr'+(k===o.preset?' style="background:var(--accent-soft)"':'')+'><td><strong>'+nm+'</strong></td><td class="num">'+inr(a.total)+'</td><td class="num">'+inr((a.total-a.t.m)*12+(oo.contrib?a.t.c2:0))+'</td><td class="num">'+L(raised)+'</td><td class="num'+(fromRes>0?" neg":" pos")+'">'+L(fromRes)+'</td><td class="num'+(rr.surplus<0?" neg":" pos")+'">'+L(rr.surplus)+'</td><td><span class="pill '+(v.c==="no"?"crit":v.c==="mid"?"warn":"ok")+'">'+v.t+'</span></td></tr>';}).join("");
}
document.querySelectorAll("input,select").forEach(el=>el.addEventListener("input",render)); render();"""
    page("simulator.html","Try the options",sim,simjs)

    con = """<section><div class="eyebrow">What the association has signed, and what it has not</div><h1>Contracts and commitments</h1>
<p class="lead">Two contracts are two-thirds of all spending. Neither was tendered. One was never signed. The other was never signed by the association. Here is each commitment as it stands.</p>
<div class="tablewrap"><table><thead><tr><th>Service</th><th>Provider</th><th class="num">Cost per year</th><th>Contract position</th><th>What the committee is doing</th></tr></thead><tbody>
<tr><td>Facility management: housekeeping, gardeners, technicians, estate manager</td><td>Sobha Ltd (facility division)</td><td class="num">₹98 L incl. GST</td><td>No signed contract. A draft MOU from January 2026 exists, unsigned, with no price in it. Sobha bills salaries at cost plus 13% PF, plus a 15% fee, plus 18% GST: about ₹28,500 per staff member per month for 27–31 staff.</td><td>Interim agreement being completed on this draft, with a rate card, for October–March; then a tender with residents' ratings as the benchmark. Sobha bids like anyone else.</td></tr>
<tr><td>Security: 22 posts (2 supervisors, 18 guards, lifeguard, lady guard)</td><td>VEX India Securitas</td><td class="num">₹72 L + GST (≈₹85 L)</td><td>Agreement dated 16 Oct 2025, term to Nov 2027, signed by the agency only; the association's signature block is blank. Bills by the day worked. Deployment fell to 81% of contract in July and 76% in August.</td><td>Written position on the reduced deployment; the agreement's own attendance penalties applied; retender with a specification written from the survey (language, turnover, block posts, basement rounds).</td></tr>
<tr><td>Lifts and UPS maintenance</td><td>Lift contractor</td><td class="num">₹16 L</td><td>Half-yearly contract, ₹8 L paid in June and December. Lifts were the lowest-rated service in the survey. ₹6.75 L was spent on batteries last year while some were under warranty.</td><td>Monthly uptime log from October; root-cause report on the worst machines; contract rebid on uptime with penalties.</td></tr>
<tr><td>Sewage and water treatment operation</td><td>STP/WTP contractor</td><td class="num">₹9 L</td><td>Cost has doubled in two years (₹4.7 L to ₹9.2 L). Residents report odour near Wing 1 and in basements.</td><td>Odour audit; retender with odour standards and a chemical schedule.</td></tr>
<tr><td>Electricity</td><td>BESCOM</td><td class="num">₹60 L</td><td>Utility; no contract to negotiate. Corridor and staircase timers reported faulty.</td><td>Timer re-commissioning; energy audit; solar feasibility to come back to the General Body.</td></tr>
<tr><td>Water</td><td>BWSSB</td><td class="num">₹22 L</td><td>New Cauvery connection; a permanent line item from this year.</td><td>Meter and leak audit; maximise treated water for gardens and flushing.</td></tr>
<tr><td>Waste collection, pest control, consumables</td><td>Various</td><td class="num">≈₹11 L</td><td>Monthly arrangements without rate contracts. Pest control was the second-lowest-rated service.</td><td>Annual rate contracts with three quotes; pest vendor's schedule audited; drain-line treatment added.</td></tr>
</tbody></table></div></section>
<section><h2>Two things owners should know about the Sobha arrangement</h2>
<div class="callout"><strong>The deposit.</strong> When Sobha returned the corpus in 2023–24 it kept ₹91 L. Sobha treats this as its security for the facility service, and since June 2026 it has been adjusting its unpaid monthly bills against it and re-crediting them when the association pays. Its ledger shows about ₹75 L; the association's books show ₹90 L. The bye-laws do not permit association funds to sit with a developer; how and when the balance comes back is part of the interim agreement now being negotiated.</div>
<div class="callout"><strong>Purchases.</strong> Under the working arrangement, Sobha's estate manager buys consumables and spares on the association's account. That is where last year's monthly bulb purchases and above-market prices, noted by the Sub-Committee, came from. From September, any purchase above ₹25,000 needs three quotes before it is paid, and the monthly list is published.</div></section>
<section><h2>A tax point that affects the numbers</h2><p>The association is registered for GST. Security services bought from a proprietorship by a registered body are taxed under "reverse charge": the association must pay the 18% itself, and the agency should not charge it. The agency has been charging it, about ₹1 L a month, and the association has been paying it. The committee's tax adviser is computing what the association owes directly since November 2025 and what it can recover or set off. The net cost is small; the interest and the paperwork are not. It is mentioned here because it will appear in the accounts and owners should not be surprised by it.</p></section>
<section><h2>The rules being written</h2><ol class="steps"><li>Every contract worth more than ₹25 L a year goes to the General Body, whatever the monthly bill looks like.</li><li>Three quotes above ₹25,000; vendor identity and bank account verified before the first payment; no payments to personal accounts.</li><li>A contract register with renewal dates and a 90-day tender trigger, so nothing rolls over by default again.</li><li>The association issues its own contract form; vendors sign ours.</li></ol></section>"""
    page("contracts.html","Contracts and commitments",con)

    ACT=[("Money and the meeting",[("Special General Body Meeting on 18–19 October: notice by 12 September, full pack by 4 October","Committee","Sep–Oct"),("Reconciled FY 2026–27 budget from the accountant's statements and bank figures, shared with the Sub-Committee for comment first","Treasurer","by 26 Sep"),("Written GST advice on whole-amount vs excess taxation and input credit, before the notice","Tax adviser","by 10 Oct"),("Until the General Body decides, the shortfall is met from the reserves; the amount drawn is reported on the reserves page each month","Treasurer","monthly"),("Explain the ₹61 L difference between the books and the bank on HDFC deposits, and obtain ICICI maturity dates","Treasurer","Sep"),("Corpus bridge from ₹11.76 Cr at handover to today's deposits, from the audited balance sheets","Treasurer, auditor","in the pack")]),
    ("Accountability",[("Sub-Committee report sent to the previous committee for written responses on each point within 21 days; responses published with the pack","President","by 29 Sep"),("Written questions to the auditor on the corpus withdrawals, the payment without an invoice, payments to personal accounts and the security GST","Committee","by 26 Sep"),("General Body asked to approve an independent review of the flagged transactions, with a defined scope and budget","Committee","SGBM"),("Nobody named or blamed ahead of findings; process and dates communicated instead","Committee","standing")]),
    ("Contracts",[("Interim agreement with Sobha for October–March with a rate card and headcount","Secretary","Sep"),("Facility-management tender with service standards from the survey","Secretary, engineering group","before SGBM"),("Security: written position on deployment, penalties applied, retender specification","Secretary","Sep–Oct"),("Lift contract rebid on uptime; monthly lift log published from October","Engineering group","Oct"),("STP: odour audit, retender with standards","Engineering group","Oct")]),
    ("Services residents asked about",[("Complaint standard in MyGate: acknowledged in 4 working hours, updated every 48 hours, closed on your confirmation; monthly numbers published","Facility manager","Oct"),("Pest control: vendor's schedule audited, mosquito source reduction, published fogging calendar, drain-line treatment","Facility manager","Sep–Oct"),("Play area: hardened sand and exposed pipes inspected and fixed","Engineering group","Sep"),("Corridor and staircase light timers re-commissioned","Facility manager","Sep"),("Tennis coaching slots; clubhouse booking through MyGate; gym and AC servicing","Secretary","Oct"),("Arrears: notices to the 30 flats with dues; owners more than 60 days in arrears at year-end cannot vote in or stand for the next election (bye-law 7)","Treasurer","Sep")]),
    ("Rules for the future",[("Financial controls policy: contract thresholds by annual value, three quotes, vendor checks, monthly reporting, accounts published by 31 May","Treasurer","SGBM"),("Corpus policy: interest is income, principal is not; two signatures; monthly deposit statement","Treasurer","SGBM"),("Monthly transparency pack on MyGate and on these pages by the 10th","Secretary","from Oct"),("Sinking fund from next year for lifts, painting and waterproofing","Committee","next AGM")])]
    arows="".join('<section><h2>'+g+'</h2><div class="tablewrap"><table><thead><tr><th>Action</th><th>Who</th><th>When</th></tr></thead><tbody>'+"".join('<tr><td>'+a+'</td><td>'+w+'</td><td>'+d+'</td></tr>' for a,w,d in items)+'</tbody></table></div></section>' for g,items in ACT)
    act='<section><div class="eyebrow">The committee\'s commitments, in public</div><h1>What the committee is doing</h1><p class="lead">Every item has an owner and a date. Progress is marked here each month. Anything that slips stays on the list with its reason.</p></section>'+arows+'<section><p class="small">"Engineering group" is the volunteer engineering sub-committee; "facility manager" is Sobha\'s estate manager working to the committee\'s instructions. Personal names are not used on these pages.</p></section>'
    page("actions.html","What the committee is doing",act)
